package org.blueo.commons.test.object;

// Generated 2015-4-14 23:20:03 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * YzpCodeLog generated by hbm2java
 */
@Entity
@Table(name = "yzp_code_log", schema = "public")
public class YzpCodeLog extends BasePo implements java.io.Serializable {
	private static final long serialVersionUID = 7661319143392938818L;
	
	private String phone;
	private String code;
	private Date sendTime;

	public YzpCodeLog() {
	}

	public YzpCodeLog(Long id) {
		this.id = id;
	}

	public YzpCodeLog(Long id, String phone, String code, Date sendTime) {
		this.id = id;
		this.phone = phone;
		this.code = code;
		this.sendTime = sendTime;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "code", length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "send_time", length = 29)
	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

}
